### ISSUE TITLE
RN example fail in `yarn collect-fbts` script

### ISSUE THREAD

**Issue by hyochan** [facebook/fbt#141]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/27461460/81540743-0aeab280-93ad-11ea-8a56-262bb09b3404.png)

When running `yarn collect-fbts` after `yarn manifest`, it throws error like above.

## To Reproduce

1, `git clone https://github.com/facebook/fbt.git`
2. `git checkout rn-demo-app`
3. `yarn`
4. `yarn manifest`
5. `yarn collect-fbts`

## Expected behavior

Correctly completes the script. 

## Link to repo (highly encouraged) or paste

[official rn demo app](https://github.com/facebook/fbt/tree/rn-demo-app)

## envinfo

```bash

  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 641.93 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
```

**Comment by jatinsandilya** [comment]
I was facing the same issue. 
Updating the `package.json` to `"fb-tiger-hash": "0.1.1"` solved it for me.

**Comment by hyochan** [comment]
@jatinsandilya Just tried to downgrade this to `0.1.1` and still having same problem.

![image](https://user-images.githubusercontent.com/27461460/81562394-bb69ae00-93cf-11ea-93d1-74954a791230.png)

**Comment by dalmendray** [comment]
@hyochan, we updated the path of the `hashPhrases` module here: https://github.com/facebook/fbt/commit/27bb2e3eca1a18b01448646f77e2420c5ebc142f.

A fix is up, but if you want to get it working now, please just update the path in the `collect-fbts` script from:

`"collect-fbts": "babel-node ./node_modules/babel-plugin-fbt/bin/collectFBT --hash-module 'fb-tiger-hash/hashPhrases' --react-native-mode --manifest < i18n/fbt/.src_manifest.json > i18n/fbt/.source_strings.json",`

to:

"collect-fbts": "babel-node ./node_modules/babel-plugin-fbt/bin/collectFBT --hash-module 'fb-tiger-hash/src/hashPhrases' --react-native-mode --manifest < i18n/fbt/.src_manifest.json > i18n/fbt/.source_strings.json",

And also, update the `fb-tiger-hash` lib to `0.1.6`

**Comment by dalmendray** [comment]
Fix landed https://github.com/facebook/fbt/commit/ce9ca9356a83a3b00e4699910a5e748803d19814
