### ISSUE TITLE
Can we have better documentation on fbt internationalization.

### ISSUE THREAD

**Issue by pranjalBakshi** [facebook/fbt#166]

**Comment by pranjalBakshi** [comment]
Can we have better documentation on how can we use this demo-app. Also how can we use npm instead of yarn

**Comment by kayhadrin** [comment]
Hi @pranjalBakshi,

I'll submit a documentation update to better explain how to start the demo-app in the command-line interface.

> Also how can we use npm instead of yarn [?]

`yarn` is the main npm dependency management tool used at Facebook that was created to get around some limitations of `npm`.
See this post: https://engineering.fb.com/web/yarn-a-new-package-manager-for-javascript/

Could you share your thoughts of why we should support `npm` instead?

**Comment by jrwats** [comment]
Closing @pranjalBakshi - feel free to re-open if you have any more questions
