### ISSUE TITLE
[Docs] Error: Cannot find module 'fb-tiger-hash'

### ISSUE THREAD

**Issue by retyui** [facebook/fbt#258]
## To Reproduce

1. Install the latest version fbt using a documentation guide https://facebook.github.io/fbt/docs/getting_started_react_native
2. Run `yarn collect-fbts`
3. An error happend `Error: Cannot find module 'fb-tiger-hash'`

## Expected behavior

- Documentation should include a step with adding a `fb-tiger-hash` module 
or
- a `collect-fbts` script  should be without `--hash-module fb-tiger-hash` param

## Link to repo (highly encouraged) or paste

...

## envinfo

```bash
npx: installed 1 in 0.759s

  System:
    OS: Linux 5.4 Linux Mint 20.2 (Uma)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 1.62 GB / 15.46 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 14.17.5 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.14 - /usr/bin/npm
    Watchman: 20210110.135312.0 - /usr/local/bin/watchman

```

**Comment by kayhadrin** [comment]
It seems to me that the [doc already recommends](https://github.com/facebook/fbt/blame/master/docs/getting_started_react_native.md#L16) to install the `fb-tiger-hash` module?
Is there an issue?

> Expected behavior: a collect-fbts script should be without --hash-module fb-tiger-hash param

Why would you expect this?
The [`collect-fbts`](https://github.com/facebook/fbt/blob/rn-demo-app/package.json#L7) yarn script is tailored for the RN demo app, and AFAICT, it works properly by generating the list of strings in `i18n/fbt/.source_strings.json`.

Maybe I'm not reproducing the issue correctly on my end. If there's still an issue, please let me know; and it'd be great to attach some error logs too. ;-)
