### ISSUE TITLE
[Docs] Search doesn't work! algolia: Index fbt does not exist

### ISSUE THREAD

**Issue by retyui** [facebook/fbt#295]
## 🐛 Bug Report

Algolia: `Index fbt does not exist`

## To Reproduce

- open https://facebook.github.io/fbt/
- try to search something
- 404 error:  ![11](https://user-images.githubusercontent.com/4661784/132952090-e7c8aaa4-8d99-4376-b92e-9e602cdd0c15.png)

## Expected behavior

Search work properly

**Comment by yangshun** [comment]
Has been fixed thanks to https://github.com/algolia/docsearch-configs/pull/4618. Huge thanks to @shortcuts!

**Comment by retyui** [comment]
just checked 
it works
