### ISSUE TITLE
Remove fbjs dependency

### ISSUE THREAD

**Issue by alexandernanberg** [facebook/fbt#321]
## 🚀 Feature Proposal

Inline the used functions from `fbjs` (`keyMirror` and `forEachObject`) and remove the dependency

## Motivation

1 less dependency is always good. `fbjs` have a bunch of dependencies too so the impact isn't small imo. 

E.g. all consumers will download these but they are never used

```
    core-js "^2.4.1"
    fbjs-css-vars "^1.0.0"
    isomorphic-fetch "^2.1.1"
    loose-envify "^1.0.0"
    object-assign "^4.1.0"
    promise "^7.1.1"
    setimmediate "^1.0.5"
    ua-parser-js "^0.7.18"
```

If you agree, I can try creating a PR inlining the functions

## Example

N/A

## Pitch

N/A

**Comment by pkqinys** [comment]
> Inline the used functions from fbjs (keyMirror and forEachObject) and remove the dependency

Makes sense to me. `FbtUtil.js` would be a good place to define port these two methods to. cc. @kayhadrin any objection?

**Comment by kayhadrin** [comment]
Sure, happy to see these dependencies removed; please ensure that Flow types are still preserved though! :-)

Code pointers:

- [keyMirror.js](https://github.com/facebook/fbjs/blob/d8f0f430a689ee1e5bb070d501155fa29e329019/packages/fbjs/src/key-mirror/keyMirror.js)
- [forEachObject.js](https://github.com/facebook/fbjs/blob/main/packages/fbjs/src/functional/forEachObject.js)
