### ISSUE TITLE
Fix Support for Shared Enum Typescript/ES6 Import/export syntax with Babel 7

### ISSUE THREAD

**Issue by sb55555** [facebook/fbt#334]
## 🐛 Bug Report

Hello, according to the doc it's [possible](https://facebook.github.io/fbt/docs/enums) to define Enums in Typescript ES6 in standalone files but currently this is not working :

```
// Example$FbtEnum.js
const Example$FbtEnum = {
  LINK: "link",
  PAGE: "page",
  PHOTO: "photo",
  POST: "post",
  VIDEO: "video",
};
export default Example$FbtEnum;

// Demo.react.js
import Example$FbtEnum from 'Example$FbtEnum';
<fbt desc="Example enum">
  <fbt:param name="name">{this.state.ex2Name}</fbt:param>
  has a
  <fbt:enum
    enum-range={Example$FbtEnum}
    value={this.state.exampleObject}
  />
  to share!
</fbt>
```
## To Reproduce

```
> fbt-manifest --src app/src

/Users/john/Desktop/app/src/discover/Example$FbtEnum.ts:14
export default Category$FbtEnum;
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/Users/john/Desktop/app/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/john/Desktop/app/node_modules/babel-plugin-fbt/dist/bin/manifest.js:57:17)
```
After investigations, I found out the issue :
`fbt-manifest` depends on Babel v7 to parse typescript files, but in v7 some arguments 
to [`@babel/register`](https://github.com/facebook/fbt/blob/main/packages/babel-plugin-fbt/src/bin/manifestUtils.js#L35) are missing.

To enable Babel 7 to understand typescript we need to add '.ts' and '.tsx' extensions to babel register
Also due to behaviour in v7, we need to add `ignore: [/node_modules/]` or babel won't compile ts outside its current directory. see https://github.com/babel/babel/issues/8321#issuecomment-464932499

## Expected behavior

Typescript files should be understood and compiled when required() here: 
https://github.com/facebook/fbt/blob/main/packages/babel-plugin-fbt/src/bin/manifestUtils.js#L60

## The FIX

When adding the following as parameters of @babel/register, after [this line](https://github.com/facebook/fbt/blob/main/packages/babel-plugin-fbt/src/bin/manifestUtils.js#L38) it fixes the issue and the example work on the latest version.
```
    // copied default extensions and added '.ts', '.tsx'
    extensions: ['.js', '.json', '.node', '.jsx', '.es6', '.es', '.mjs', '.cjs', '.ts', '.tsx'],
    // without this babel 7 won't compile ts outside its current directory
    // see https://github.com/babel/babel/issues/8321#issuecomment-464932499
    ignore: [/node_modules/],
```

**Comment by pkqinys** [comment]
@kayhadrin fbt plugins never intend to support typescript, right?

**Comment by kayhadrin** [comment]
It was only designed to read JS code up to something like ES6 syntax, not TS.

Ideally, we'd just run the `fbt-manifest` and `fbt-collect` scripts on "vanilla" JS code that follows ES6.
But it's easy to imagine that writing temporary files on disk just to do this can be challenging in an e2e JS transpilation process.

We should facilitate this by considering the following options:
- add support for TS file parsing
- expose APIs for fbt-manifest, fbt-collect, etc... that receive code as a Babel AST directly. 
This would make it easier to integrate with various JS transpilation pipelines. E.g. Webpack, Gulp, etc...
Currently, we have only done this for the `babel-plugin-fbt` module in our demo-app

@sb55555 Would you be able to create a PR based on your findings?

**Comment by kayhadrin** [comment]
Thanks @sb55555 for including so much context info into this bug report!
